# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5831f48774bc46b509ac36fcdbd860640bb4e4fbcf7e373105b9a2808daf3743c9c7897e5d0ca239b2a0a0b3f1cd6d14d16d07bcff66e6485620c9552c6430c9

test:
  secret_key_base: 2ae7f9929c42f9e23cf5a165c36b793b030b28a6528158f475c5ccc6e488d3ca93e0a0289a5c9b6e5bae0581ead74c4c0de19ca3c4286e205a9ace353838c341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
